languageCode = "en-us"
title = "My New Netlify Victor Hugo Site"

DefaultContentLanguage = "en"

[languages]
  [en]
	  languageName = "English"
	  weight = 1
    contentDir = "content"
  [fr]
	  languageName = "Français"
	  weight = 2
    contentDir = "content/fr"
